site_name: Arkeo All-in-One API Documentation (v0.1)

theme:
  name: material
  icon:
    annotation: material/arrow-right-circle 
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.suggest
    - content.footnote.tooltips
    - content.code.annotate
    - content.code.copy
    - content.image.zoom
    - content.action.copy
    - content.icons
    
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: false
      linenums: false
      guess_lang: false
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - API Overview: getting-started/overview.md
    - Protocol: getting-started/protocol.md
  - API Reference:
    - MAIN: main/index.md
    - ROUTINE: 
      - Overview: routine/index.md
      - Connection Test: routine/connection_test.md
      - JV Routine: routine/jv.md
      - IPCE Routine: routine/ipce.md
      - Resistivity Routine: routine/resistivity.md
      - Luminescence Routine: routine/luminescence.md
      - Transient Photo Response Routine: routine/tpr.md
      - Impedance Routine: routine/impedance.md
    - TMPCTL: tmpctl/index.md
    - MUX: mux/index.md
  - Examples:
      - Python Example: examples/python.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - assets/stylesheets/extra.css